name: Run Smoke Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download ChromeDriver
        run: |
          # Set version to the version of Chrome you are using
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo "Downloading ChromeDriver version $CHROMEDRIVER_VERSION"
          
          # Download and extract the chromedriver
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d ./drivers/
          rm chromedriver_linux64.zip

      - name: Make chromedriver executable
        run: chmod +x ./drivers/chromedriver

      - name: Run Smoke TestNG Suite
        run: mvn clean test -DsuiteXmlFile=smoke.xml
