name: Run Smoke Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Download ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          mv chromedriver /home/runner/work/Java_Frame_Sample/Java_Frame_Sample/drivers/
          chmod +x /home/runner/work/Java_Frame_Sample/Java_Frame_Sample/drivers/chromedriver

    - name: Run Smoke TestNG Suite
      run: mvn clean test -DsuiteXmlFile=smoke.xml
